# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca7809c5f94ce35b5270294f679f8871213c85be3abe8b1c967ce6753f6102472e05c24fda878a952650bdfa814fd48653c602bbc62609f9f6eec4aef476767

test:
  secret_key_base: 724d43ca68f4e86ec0ef481634a81da32e76db683430508c2f6bcb154866380e49646cc1a34672a60ed5c064a1ba393d38c430eff30bf9f8004abbfce4f4f12f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
